# Generated by Django 6.0.2 on 2026-04-23 17:48

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Esteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Esteira')),
                ('tipo', models.CharField(choices=[('INICIAL', 'Inicial'), ('EM_ANDAMENTO', 'Em andamento'), ('SUCESSO', 'Sucesso'), ('INSUCESSO', 'Insucesso')], max_length=20, verbose_name='Tipo')),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='Ordem do funil')),
                ('ativo', models.BooleanField(default=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esteiras', to='usuarios.carteira')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esteiras', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Parceiro')),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parceiros', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Produto')),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_min', models.PositiveSmallIntegerField(verbose_name='Min. Prazo')),
                ('prazo_max', models.PositiveSmallIntegerField(verbose_name='Max. Prazo')),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comissão %')),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.empresa')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='vendas.parceiro')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='vendas.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=50, verbose_name='Nr. Contrato')),
                ('produto_nome', models.CharField(max_length=150, verbose_name='Produto nome')),
                ('parceiro_nome', models.CharField(max_length=150, verbose_name='Parceito nome')),
                ('prazo', models.PositiveSmallIntegerField(verbose_name='Prazo')),
                ('parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Parcela')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Contrato')),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa')),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comissão aplicada %')),
                ('carteira_nome', models.CharField(max_length=50, verbose_name='Carteira')),
                ('equipe_nome', models.CharField(max_length=100, verbose_name='Equipe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Boletagem')),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='agenda.agenda')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='core.empresa')),
                ('esteira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='vendas.esteira')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='vendas.oferta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, max_length=1024, verbose_name='Comentário')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('esteira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.esteira')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='vendas.venda')),
            ],
        ),
        migrations.AddConstraint(
            model_name='parceiro',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('empresa'), name='unique_name_emrpesa'),
        ),
        migrations.AddConstraint(
            model_name='oferta',
            constraint=models.UniqueConstraint(fields=('empresa', 'produto', 'parceiro', 'prazo_min', 'prazo_max'), name='unique_oferta_empresa_produto_parceiro_prazo'),
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.UniqueConstraint(fields=('empresa', 'contrato', 'cliente', 'esteira'), name='unique_contrato_empresa_cliente_esteira'),
        ),
    ]
