# Generated by Django 6.0.2 on 2026-03-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='contrato',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Nr. Contrato'),
            preserve_default=False,
        ),
    ]
