# Generated by Django 6.0.2 on 2026-04-24 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='carteira',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='carteira', to='usuarios.carteira'),
            preserve_default=False,
        ),
    ]
