# Generated by Django 6.0.2 on 2026-03-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='parceiro_nome',
            field=models.CharField(default='', max_length=150, verbose_name='Parceito nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='produto_nome',
            field=models.CharField(default='', max_length=150, verbose_name='Produto nome'),
            preserve_default=False,
        ),
    ]
