# Generated by Django 6.0.2 on 2026-03-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_empresa_cnpj'),
        ('vendas', '0003_venda_parceiro_nome_venda_produto_nome'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='oferta',
            name='unique_oferta_empresa_produto_parceiro',
        ),
        migrations.AddConstraint(
            model_name='oferta',
            constraint=models.UniqueConstraint(fields=('empresa', 'produto', 'parceiro', 'prazo_min', 'prazo_max'), name='unique_oferta_empresa_produto_parceiro_prazo'),
        ),
    ]
