# Generated by Django 6.0.2 on 2026-03-11 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_remove_oferta_unique_oferta_empresa_produto_parceiro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='carteira',
            new_name='carteira_nome',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='equipe',
            new_name='equipe_nome',
        ),
        migrations.AlterField(
            model_name='histvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='vendas.venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='contrato',
            field=models.CharField(max_length=50, verbose_name='Nr. Contrato'),
        ),
    ]
