# Generated by Django 6.0.2 on 2026-03-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_rename_carteira_venda_carteira_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='data_venda',
            new_name='created_at',
        ),
    ]
