# Generated by Django 6.0.2 on 2026-03-11 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_situacao_tipo'),
        ('clientes', '0009_alter_endereco_uf'),
        ('core', '0003_alter_empresa_cnpj'),
        ('vendas', '0007_venda_unique_contrato_empresa_esteira'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='venda',
            name='unique_contrato_empresa_esteira',
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.UniqueConstraint(fields=('empresa', 'contrato', 'cliente', 'esteira'), name='unique_contrato_empresa_cliente_esteira'),
        ),
    ]
