# Generated by Django 6.0.2 on 2026-03-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_remove_venda_unique_contrato_empresa_esteira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='taxa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa'),
            preserve_default=False,
        ),
    ]
