# Generated by Django 6.0.2 on 2026-03-13 18:45

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_empresa_cnpj'),
        ('vendas', '0009_venda_taxa'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parceiro',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('empresa'), name='unique_name_emrpesa'),
        ),
    ]
