# Generated by Django 6.0.2 on 2026-02-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
