# Generated by Django 6.0.2 on 2026-04-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_viewpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewpermission',
            name='roles',
            field=models.JSONField(default=['ADM']),
        ),
    ]
