# Generated by Django 6.0.2 on 2026-02-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.SlugField(blank=True, max_length=14, null=True),
        ),
    ]
