# Generated by Django 6.0.2 on 2026-04-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_viewpermission_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewpermission',
            name='roles',
            field=models.JSONField(default=list),
        ),
    ]
