# Generated by Django 6.0.2 on 2026-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_viewpermission_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewpermission',
            name='app_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
