# Generated by Django 6.0.2 on 2026-05-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_viewpermission_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewpermission',
            name='app_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
