# Generated by Django 6.0.2 on 2026-05-04 18:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_empresa_cnpj_empresa_unique_cnpj_not_null'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='unique_nome_case_insensitive'),
        ),
    ]
