# Generated by Django 6.0.2 on 2026-04-23 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, verbose_name='Tipo Pessoa')),
                ('documento', models.CharField(help_text='CPF (11) ou CNPJ (14) somente números', max_length=14, verbose_name='Documento')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Mãe')),
                ('nome_pai', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Pai')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável')], max_length=20, null=True, verbose_name='Estado Civil')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255)),
                ('tipo', models.CharField(blank=True, choices=[('PESSOAL', 'Pessoal'), ('CORPORATIVO', 'Corporativo')], max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logra.')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=10, verbose_name='Cep')),
                ('tipo', models.CharField(choices=[('RESIDENCIAL', 'Residencial'), ('COMERCIAL', 'Comercial')], max_length=15, verbose_name='Tipo Endereco')),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, db_index=True, max_length=11)),
                ('tipo', models.CharField(blank=True, choices=[('FIXO', 'Fixo'), ('CELULAR', 'Celular'), ('CORPORATIVO', 'Corporativo')], max_length=15)),
                ('whats_app', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='clientes.cliente')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('empresa', 'documento'), name='unique_cpf_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(fields=('cliente', 'email', 'tipo'), name='unique_email_cliente'),
        ),
        migrations.AddConstraint(
            model_name='endereco',
            constraint=models.UniqueConstraint(fields=('cliente', 'logradouro', 'numero', 'cep', 'tipo'), name='unique_endereco_cliente_tipo'),
        ),
        migrations.AddConstraint(
            model_name='telefone',
            constraint=models.UniqueConstraint(fields=('cliente', 'telefone'), name='unique_telefone_cliente'),
        ),
    ]
