# Generated by Django 6.0.2 on 2026-05-07 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_banco', models.CharField(max_length=5, verbose_name='Código Banco')),
                ('nome_banco', models.CharField(max_length=50, verbose_name='Nome Banco')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cod_banco', 'nome_banco'), name='unique_cod_nome')],
            },
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=10, verbose_name='Agencia')),
                ('conta', models.CharField(max_length=10, verbose_name='Conta')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.bancos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancario', to='clientes.cliente')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cliente', 'banco', 'agencia', 'conta'), name='unique_cliente_banco_agencia_conta')],
            },
        ),
    ]
