# Generated by Django 6.0.2 on 2026-05-08 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_bancos_dadosbancarios'),
        ('core', '0008_empresa_unique_nome_case_insensitive'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dadosbancarios',
            name='unique_cliente_banco_agencia_conta',
        ),
        migrations.AddField(
            model_name='dadosbancarios',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_bancarios', to='clientes.cliente'),
        ),
        migrations.AddIndex(
            model_name='dadosbancarios',
            index=models.Index(fields=['empresa', 'cliente', 'banco'], name='clientes_da_empresa_6e4210_idx'),
        ),
        migrations.AddIndex(
            model_name='dadosbancarios',
            index=models.Index(fields=['empresa', 'banco'], name='clientes_da_empresa_e9713e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dadosbancarios',
            constraint=models.UniqueConstraint(fields=('empresa', 'cliente', 'banco', 'agencia', 'conta'), name='unique_empresa_cliente_banco_agencia_conta'),
        ),
    ]
