# Generated by Django 6.0.2 on 2026-02-20 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_data_nascimento_and_more'),
        ('core', '0002_empresa_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.empresa'),
            preserve_default=False,
        ),
    ]
