# Generated by Django 6.0.2 on 2026-02-21 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_empresa'),
        ('core', '0003_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('tipo', models.CharField(choices=[('PESSOAL', 'Pessoal'), ('CORPORATIVO', 'Corporativo')], max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logra.')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=10, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=10, verbose_name='Cep')),
                ('tipo', models.CharField(choices=[('RESIDENCIAL', 'Residencial'), ('COMERCIAL', 'Comercial')], max_length=15, verbose_name='Tipo Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(db_index=True, max_length=11)),
                ('tipo', models.CharField(choices=[('FIXO', 'Fixo'), ('CELULAR', 'Celular'), ('CORPORATIVO', 'Corporativo')], max_length=15)),
                ('whats_app', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(help_text='CPF (11) ou CNPJ (14) somente números', max_length=14, verbose_name='Documento'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('empresa', 'documento'), name='unique_cpf_por_empresa'),
        ),
        migrations.AddField(
            model_name='email',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='clientes.cliente'),
        ),
        migrations.AddConstraint(
            model_name='endereco',
            constraint=models.UniqueConstraint(fields=('cliente', 'logradouro', 'numero', 'cep', 'tipo'), name='unique_endereco_cliente_tipo'),
        ),
    ]
