# Generated by Django 6.0.2 on 2026-05-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_dadosbancarios_unique_cliente_banco_agencia_conta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancos',
            name='cor_primaria',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor 1'),
        ),
        migrations.AddField(
            model_name='bancos',
            name='cor_secundaria',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor 2'),
        ),
    ]
