# Generated by Django 6.0.5 on 2026-05-18 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_bancos_cor_primaria_bancos_cor_secundaria'),
        ('core', '0008_empresa_unique_nome_case_insensitive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=15, null=True, verbose_name='Matricula')),
                ('instituidor', models.CharField(blank=True, max_length=15, null=True, verbose_name='Instituidor')),
                ('convenio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Convenio')),
                ('orgao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Orgao')),
                ('sit_func', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sit. Funcional')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salário Bruto')),
                ('margem_consig', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Margem Livre')),
                ('margem_ct', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Margem CT')),
                ('margem_ct_bn', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Margem CT Beneficio')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('referencia', models.DateField(verbose_name='Data ref.')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_financeiros', to='clientes.vinculo')),
            ],
        ),
        migrations.CreateModel(
            name='Dividas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco divida')),
                ('rubrica', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nr. Rubrica')),
                ('Tipo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo divida')),
                ('saldo_devedor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Devedor')),
                ('prazo_faltante', models.PositiveIntegerField(verbose_name='Prazo')),
                ('parcela', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Parcela')),
                ('contrato', models.CharField(blank=True, max_length=12, null=True, verbose_name='Nr. Contrato')),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taxa')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('referencia', models.DateField(verbose_name='Data ref.')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividas_financeiras', to='clientes.vinculo')),
            ],
        ),
        migrations.AddIndex(
            model_name='vinculo',
            index=models.Index(fields=['empresa', 'cliente', 'matricula', 'convenio', 'sit_func'], name='clientes_vi_empresa_0ba195_idx'),
        ),
        migrations.AddConstraint(
            model_name='vinculo',
            constraint=models.UniqueConstraint(fields=('empresa', 'cliente', 'matricula'), name='unique_vinculo'),
        ),
    ]
