# Generated by Django 6.0.2 on 2026-02-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_email_endereco_telefone_alter_cliente_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PESSOAL', 'Pessoal'), ('CORPORATIVO', 'Corporativo')], max_length=11),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='telefone',
            field=models.CharField(blank=True, db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='tipo',
            field=models.CharField(blank=True, choices=[('FIXO', 'Fixo'), ('CELULAR', 'Celular'), ('CORPORATIVO', 'Corporativo')], max_length=15),
        ),
    ]
