# Generated by Django 6.0.2 on 2026-02-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_email_email_alter_email_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=200, verbose_name='Cidade'),
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.UniqueConstraint(fields=('cliente', 'email', 'tipo'), name='unique_email_cliente'),
        ),
        migrations.AddConstraint(
            model_name='telefone',
            constraint=models.UniqueConstraint(fields=('cliente', 'telefone'), name='unique_telefone_cliente'),
        ),
    ]
