# Generated by Django 6.0.5 on 2026-05-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_vinculo_financeiro_dividas_and_more'),
        ('core', '0008_empresa_unique_nome_case_insensitive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dividas',
            new_name='Divida',
        ),
    ]
