# Generated by Django 6.0.5 on 2026-05-22 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_rename_dividas_divida'),
        ('core', '0008_empresa_unique_nome_case_insensitive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa')),
                ('chassi', models.CharField(blank=True, max_length=15, null=True, verbose_name='Chassi')),
                ('renavan', models.CharField(blank=True, max_length=20, null=True, verbose_name='Renavan')),
                ('ano_mod', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano mod')),
                ('ano_fab', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano Fab')),
                ('marca', models.CharField(blank=True, max_length=20, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Modelo')),
                ('cat', models.CharField(blank=True, choices=[('CARROS', 'Carros, Vans e Utilitarios'), ('MOTO', 'Moto'), ('CAMINHOES', 'Caminhoes')], max_length=20, null=True, verbose_name='Categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
    ]
