# Generated by Django 6.0.2 on 2026-02-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_endereco_cidade_email_unique_email_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
