# Generated by Django 6.0.5 on 2026-05-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_veiculos'),
        ('core', '0008_empresa_unique_nome_case_insensitive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Veiculos',
            new_name='Veiculo',
        ),
    ]
