# Generated by Django 6.0.2 on 2026-02-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_telefone_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
