# Generated by Django 6.0.5 on 2026-05-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_rename_veiculos_veiculo'),
        ('core', '0008_empresa_unique_nome_case_insensitive'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['empresa', 'cliente', 'placa'], name='clientes_ve_empresa_d1759b_idx'),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(fields=('empresa', 'cliente', 'placa'), name='unique_veiculo'),
        ),
    ]
