# Generated by Django 6.0.2 on 2026-03-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_endereco_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=300, verbose_name='Cidade'),
        ),
    ]
