# Generated by Django 6.0.5 on 2026-06-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_veiculo_clientes_ve_empresa_d1759b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Chassi'),
        ),
    ]
