# Generated by Django 6.0.2 on 2026-04-23 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Carteira')),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('situacoes', models.ManyToManyField(through='agenda.CarteiraSituacao', to='agenda.situacao')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='Data Criacao')),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('ADM', 'Administrador'), ('DIRETOR', 'Diretor'), ('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor'), ('AGENTE', 'Agente'), ('VISITANTE', 'Visitante')], max_length=50, verbose_name='Perfil')),
                ('escopo', models.CharField(choices=[('GLOBAL', 'Global'), ('CARTEIRA', 'Carteira'), ('EQUIPE', 'Equipe'), ('PROPRIO', 'Próprio')], max_length=20)),
                ('data_create', models.DateTimeField(auto_now=True, verbose_name='Data Criacao')),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-mail')),
                ('nascimento', models.DateField(verbose_name='Nascimento')),
                ('cpf', models.CharField(max_length=11, verbose_name='Cpf')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.carteira')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.equipe')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfil')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['carteira'],
            },
        ),
        migrations.CreateModel(
            name='AgentePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.agente')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
            options={
                'verbose_name': 'Agente - Perfil',
                'verbose_name_plural': 'Agentes - Perfis',
                'unique_together': {('agente', 'perfil')},
            },
        ),
    ]
