# Generated by Django 6.0.2 on 2026-05-04 18:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
        ('core', '0008_empresa_unique_nome_case_insensitive'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carteira',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('empresa'), name='unique_nome_empresa_case_insensitive'),
        ),
    ]
