# Generated by Django 6.0.2 on 2026-03-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='carteira',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.carteira'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agente',
            name='equipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.equipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agente',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfil'),
            preserve_default=False,
        ),
    ]
