# Generated by Django 6.0.2 on 2026-05-04 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_carteira_unique_nome_empresa_case_insensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='carteira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.carteira'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.equipe'),
        ),
    ]
