# Generated by Django 6.0.2 on 2026-04-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_agente_carteira_alter_agente_equipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='escopo',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('CARTEIRA', 'Carteira'), ('PROPRIO', 'Próprio')], default='GLOBAL', max_length=20),
            preserve_default=False,
        ),
    ]
