# Generated by Django 6.0.2 on 2026-04-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_escopo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='escopo',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('CARTEIRA', 'Carteira'), ('EQUIPE', 'Equipe'), ('PROPRIO', 'Próprio')], max_length=20),
        ),
    ]
