# Generated by Django 6.0.2 on 2026-04-16 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_empresa_cnpj'),
        ('usuarios', '0005_alter_perfil_escopo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
            preserve_default=False,
        ),
    ]
