# Generated by Django 6.0.2 on 2026-04-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_equipe_empresa_perfil_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Perfil'),
        ),
    ]
