# Generated by Django 6.0.2 on 2026-04-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_perfil_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='codigo',
            new_name='nome_perfil',
        ),
    ]
