# Generated by Django 6.0.2 on 2026-04-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_rename_codigo_perfil_nome_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nome_perfil',
        ),
        migrations.AddField(
            model_name='perfil',
            name='codigo',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('DIRETOR', 'Diretor'), ('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor'), ('AGENTE', 'Agente'), ('VISITANTE', 'Visitante')], default='ADM', max_length=50, verbose_name='Perfil'),
            preserve_default=False,
        ),
    ]
