# Generated by Django 6.0.2 on 2026-04-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_alter_situacao_unique_together_and_more'),
        ('usuarios', '0009_remove_perfil_nome_perfil_perfil_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='situacoes',
            field=models.ManyToManyField(through='agenda.CarteiraSituacao', to='agenda.situacao'),
        ),
    ]
