# Generated by Django 6.0.2 on 2026-04-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acionamento', models.DateTimeField(auto_now_add=True, verbose_name='Data Acionamento')),
                ('data_finalizado', models.DateTimeField(blank=True, null=True, verbose_name='Data Finalizado')),
                ('comentario', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Comentario')),
            ],
            options={
                'ordering': ['-data_acionamento'],
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone de Contato')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data Entrada')),
                ('data_hora_retorno', models.DateTimeField(blank=True, null=True, verbose_name='Retorno Chamada')),
                ('data_finalizado', models.DateTimeField(blank=True, null=True, verbose_name='Data Finalizado')),
                ('agenda_ativa', models.BooleanField(default=True)),
                ('modo', models.CharField(max_length=50, verbose_name='Modo Atendimento')),
                ('canal', models.CharField(max_length=50, verbose_name='Canal Atendimento')),
                ('equipe_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil_nome', models.CharField(blank=True, max_length=50, null=True)),
                ('carteira_nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='CarteiraSituacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Situacao')),
                ('tipo', models.CharField(choices=[('INICIAL', 'Inicial'), ('CURSO', 'Em Atendimento'), ('AGENDA', 'Agendamento'), ('INSUCESSO', 'Insucesso'), ('SUCESSO', 'Sucesso'), ('SEMCONTATO', 'Sem Contato'), ('OUTRO', 'Outro')], max_length=15, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
    ]
