# Generated by Django 6.0.2 on 2026-02-27 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_perfil_grupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Situacao')),
                ('tipo', models.CharField(choices=[('INICIAL', 'Inicial'), ('AGENDA', 'Agendamento'), ('INSUCESSO', 'Insucesso'), ('SUCESSO', 'Sucesso')], verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True)),
                ('carteira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.carteira')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('nome', 'carteira')},
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone de Contato')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data Entrada')),
                ('data_hora_retorno', models.DateTimeField(blank=True, null=True, verbose_name='Retorno Chamada')),
                ('data_finalizado', models.DateTimeField(blank=True, null=True, verbose_name='Data Finalizado')),
                ('agenda_ativa', models.BooleanField(default=True)),
                ('modo', models.CharField(max_length=50, verbose_name='Modo Atendimento')),
                ('canal', models.CharField(max_length=50, verbose_name='Canal Atendimento')),
                ('equipe_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil_nome', models.CharField(blank=True, max_length=50, null=True)),
                ('carteira_nome', models.CharField(blank=True, max_length=50, null=True)),
                ('carteira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.carteira')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.equipe')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('situacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.situacao')),
            ],
            options={
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Acionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acionamento', models.DateTimeField(auto_now_add=True, verbose_name='Data Acionamento')),
                ('data_finalizado', models.DateTimeField(blank=True, null=True, verbose_name='Data Finalizado')),
                ('comentario', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Comentario')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.situacao')),
            ],
            options={
                'ordering': ['-data_acionamento'],
            },
        ),
    ]
