# Generated by Django 6.0.2 on 2026-04-23 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('clientes', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='carteira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.carteira'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.equipe'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.perfil'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acionamento',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agenda'),
        ),
        migrations.AddField(
            model_name='carteirasituacao',
            name='carteira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.carteira'),
        ),
        migrations.AddField(
            model_name='carteirasituacao',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.situacao'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.situacao'),
        ),
        migrations.AddField(
            model_name='acionamento',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.situacao'),
        ),
        migrations.AlterUniqueTogether(
            name='carteirasituacao',
            unique_together={('carteira', 'situacao')},
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(condition=models.Q(('agenda_ativa', True)), fields=('cliente', 'carteira'), name='unique_active_agenda_per_carteira'),
        ),
        migrations.AddConstraint(
            model_name='acionamento',
            constraint=models.UniqueConstraint(condition=models.Q(('data_finalizado__isnull', True)), fields=('agenda',), name='unique_open_acionamento_per_agenda'),
        ),
    ]
