# Generated by Django 6.0.2 on 2026-02-27 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('clientes', '0009_alter_endereco_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='clientes.cliente'),
            preserve_default=False,
        ),
    ]
