# Generated by Django 6.0.2 on 2026-03-06 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agenda_cliente'),
        ('clientes', '0009_alter_endereco_uf'),
        ('usuarios', '0002_perfil_grupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situacao',
            options={'ordering': ['tipo']},
        ),
        migrations.AlterField(
            model_name='situacao',
            name='tipo',
            field=models.CharField(choices=[('INICIAL', 'Inicial'), ('CURSO', 'Em Atendimento'), ('AGENDA', 'Agendamento'), ('INSUCESSO', 'Insucesso'), ('SUCESSO', 'Sucesso')], verbose_name='Tipo'),
        ),
        migrations.AddConstraint(
            model_name='acionamento',
            constraint=models.UniqueConstraint(condition=models.Q(('data_finalizado__isnull', True)), fields=('agenda',), name='unique_open_acionamento_per_agenda'),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(condition=models.Q(('agenda_ativa', True)), fields=('cliente', 'carteira'), name='unique_active_agenda_per_carteira'),
        ),
    ]
