# Generated by Django 6.0.2 on 2026-05-05 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
        ('core', '0008_empresa_unique_nome_case_insensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacao',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa'),
        ),
    ]
