# Generated by Django 6.0.2 on 2026-03-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_situacao_options_alter_situacao_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='acionamento',
            name='unique_open_acionamento_per_agenda',
        ),
        migrations.AddConstraint(
            model_name='acionamento',
            constraint=models.UniqueConstraint(condition=models.Q(('data_finalizado__isnull', True)), fields=('agenda',), name='unique_open_acionamento_per_agenda'),
        ),
    ]
