# Generated by Django 6.0.2 on 2026-03-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_remove_acionamento_unique_open_acionamento_per_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacao',
            name='tipo',
            field=models.CharField(choices=[('INICIAL', 'Inicial'), ('CURSO', 'Em Atendimento'), ('AGENDA', 'Agendamento'), ('INSUCESSO', 'Insucesso'), ('SUCESSO', 'Sucesso')], max_length=15, verbose_name='Tipo'),
        ),
    ]
