# Generated by Django 6.0.2 on 2026-03-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_situacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacao',
            name='tipo',
            field=models.CharField(choices=[('INICIAL', 'Inicial'), ('CURSO', 'Em Atendimento'), ('AGENDA', 'Agendamento'), ('INSUCESSO', 'Insucesso'), ('SUCESSO', 'Sucesso'), ('SEMCONTATO', 'Sem Contato'), ('OUTRO', 'Outro')], max_length=15, verbose_name='Tipo'),
        ),
    ]
