# Generated by Django 6.0.2 on 2026-04-23 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_situacao_tipo'),
        ('usuarios', '0009_remove_perfil_nome_perfil_perfil_codigo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='situacao',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='carteira',
        ),
        migrations.CreateModel(
            name='CarteiraSituacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.carteira')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.situacao')),
            ],
            options={
                'unique_together': {('carteira', 'situacao')},
            },
        ),
    ]
