# Generated by Django 6.0.2 on 2026-04-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome Campanha')),
                ('modo_atendimento', models.CharField(choices=[('MANUAL', 'Manual'), ('DISCADOR', 'Discador'), ('EXLEAD', 'Lead Externo'), ('RECEPTIVO', 'Receptivo')], max_length=10, verbose_name='Modo Atendimento')),
                ('distribuicao_ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metodo_distribuicao', models.CharField(choices=[('ORDENADO', 'Ordenado'), ('ALEATORIO', 'Aleatorio')], max_length=10, verbose_name='Indice Sorteio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampanhaAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampanhaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.PositiveIntegerField(db_index=True)),
                ('tentativas', models.IntegerField(default=0)),
                ('ultima_tentativa', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
