# Generated by Django 6.0.2 on 2026-03-13 18:49

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0006_alter_situacao_tipo'),
        ('clientes', '0011_alter_endereco_cidade'),
        ('usuarios', '0003_alter_agente_carteira_alter_agente_equipe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome Campanha')),
                ('modo_atendimento', models.CharField(choices=[('MANUAL', 'Manual'), ('DISCADOR', 'Discador'), ('EXLEAD', 'Lead Externo')], max_length=10, verbose_name='Modo Atendimento')),
                ('distribuicao_ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metodo_distribuicao', models.CharField(choices=[('ORDEM', 'Ordem'), ('SEQUENCIAL', 'Sequencial')], max_length=10, verbose_name='Indice Sorteio')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.carteira')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampanhaAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanhas.campanha')),
            ],
        ),
        migrations.CreateModel(
            name='CampanhaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.PositiveIntegerField(db_index=True)),
                ('tentativas', models.IntegerField(default=0)),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.agenda')),
                ('agente_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanhas.campanha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.situacao')),
            ],
        ),
        migrations.AddConstraint(
            model_name='campanha',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('carteira'), name='unique_nome_carteira'),
        ),
        migrations.AlterUniqueTogether(
            name='campanhaagente',
            unique_together={('campanha', 'agente')},
        ),
        migrations.AddIndex(
            model_name='campanhacliente',
            index=models.Index(fields=['campanha', 'situacao', 'prioridade'], name='campanhas_c_campanh_6cc839_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campanhacliente',
            unique_together={('cliente', 'campanha')},
        ),
    ]
