# Generated by Django 6.0.2 on 2026-03-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='metodo_distribuicao',
            field=models.CharField(choices=[('ORDENADO', 'Ordenado'), ('ALEATORIO', 'Aleatorio')], max_length=10, verbose_name='Indice Sorteio'),
        ),
    ]
