# Generated by Django 6.0.2 on 2026-04-23 17:48

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_initial'),
        ('campanhas', '0001_initial'),
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='carteira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.carteira'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='campanhaagente',
            name='agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.agente'),
        ),
        migrations.AddField(
            model_name='campanhaagente',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanhas.campanha'),
        ),
        migrations.AddField(
            model_name='campanhacliente',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.agenda'),
        ),
        migrations.AddField(
            model_name='campanhacliente',
            name='agente_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campanhacliente',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanhas.campanha'),
        ),
        migrations.AddField(
            model_name='campanhacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='campanhacliente',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.situacao'),
        ),
        migrations.AddConstraint(
            model_name='campanha',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('carteira'), name='unique_nome_carteira'),
        ),
        migrations.AlterUniqueTogether(
            name='campanhaagente',
            unique_together={('campanha', 'agente')},
        ),
        migrations.AddIndex(
            model_name='campanhacliente',
            index=models.Index(fields=['campanha', 'situacao', 'prioridade'], name='campanhas_c_campanh_6cc839_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campanhacliente',
            unique_together={('cliente', 'campanha')},
        ),
    ]
