# Generated by Django 6.0.2 on 2026-03-13 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_alter_campanha_metodo_distribuicao'),
        ('usuarios', '0003_alter_agente_carteira_alter_agente_equipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhaagente',
            name='agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.agente'),
        ),
    ]
