# Generated by Django 6.0.2 on 2026-03-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0003_alter_campanhaagente_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhacliente',
            name='ultima_tentativa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
