# Generated by Django 6.0.2 on 2026-03-13 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0004_campanhacliente_ultima_tentativa'),
        ('core', '0003_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
            preserve_default=False,
        ),
    ]
