# Generated by Django 6.0.2 on 2026-04-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0005_campanha_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='modo_atendimento',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('DISCADOR', 'Discador'), ('EXLEAD', 'Lead Externo'), ('RECEPTIVO', 'Receptivo')], max_length=10, verbose_name='Modo Atendimento'),
        ),
    ]
